<div x-data="{vehicleView:'list',directoryView:'list'}">
@if($kind==='vehicle')
<div class="flex flex-wrap items-center justify-between gap-5"><div><h1 class="text-3xl font-semibold tracking-tight">{{ __('catalog.vehicles') }}</h1><p class="mt-2 text-sm text-zinc-500 dark:text-zinc-400">{{ __('catalog.fleet_directory') }}</p></div><div class="flex w-full flex-wrap items-center gap-3 lg:w-auto"><div class="min-w-0 flex-1 lg:w-64"><flux:input wire:model.live.debounce.300ms="search" icon="magnifying-glass" :placeholder="__('catalog.search_vehicles')" :aria-label="__('catalog.search_vehicles')" /></div><div class="inline-flex shrink-0 rounded-lg border border-zinc-200 p-1 dark:border-zinc-700" role="group" aria-label="{{ __('catalog.display') }}">@foreach(['list'=>'list-bullet','cards'=>'squares-2x2'] as $view=>$icon)<button type="button" @click="vehicleView='{{ $view }}'" :aria-pressed="vehicleView==='{{ $view }}'" aria-label="{{ __('catalog.view_'.$view) }}" :class="vehicleView==='{{ $view }}' ? 'bg-zinc-200 text-zinc-950 dark:bg-zinc-700 dark:text-white' : 'text-zinc-500 hover:bg-zinc-100 dark:hover:bg-zinc-800'" class="rounded-md p-2 transition"><flux:icon :name="$icon" class="size-5"/></button>@endforeach</div>@can('fleet.manage')<flux:button icon="plus" wire:click="$toggle('creating')">{{ __('catalog.add_vehicle') }}</flux:button>@endcan</div></div>
@else
<div class="flex flex-wrap items-center justify-between gap-5"><div><h1 class="text-3xl font-semibold tracking-tight">{{ __('catalog.customers') }}</h1><p class="mt-2 text-sm text-zinc-500 dark:text-zinc-400">{{ __('catalog.customer_directory') }}</p></div><div class="flex w-full flex-wrap items-center gap-3 lg:w-auto"><div class="min-w-0 flex-1 lg:w-64"><flux:input wire:model.live.debounce.300ms="search" icon="magnifying-glass" :placeholder="__('catalog.search')" :aria-label="__('catalog.search')"/></div><x-directory.toggle/>@can('customers.manage')<flux:button icon="plus" wire:click="$toggle('creating')">{{ __('catalog.add_customer') }}</flux:button>@endcan</div></div>

@endif
@if($creating)<section class="mt-6 rounded-2xl border border-zinc-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-900 sm:p-7"><h2 class="mb-5 text-xl font-semibold">{{ __('catalog.add_'.$kind) }}</h2><x-duplicate-warning :duplicates="$duplicates" />
@if($kind==='vehicle')<form wire:submit="addCategory" class="mb-6 flex flex-wrap items-end gap-3"><flux:input wire:model="categoryName" :label="__('catalog.new_category')" /><flux:button type="submit" icon="plus">{{ __('catalog.add_category') }}</flux:button></form>@else<p class="mb-5 text-sm text-zinc-500 dark:text-zinc-400">{{ __('catalog.draft_hint') }}</p>@endif
<form wire:submit="save"><x-catalog-fields :kind="$kind" :categories="$categories" :drivers="$drivers" :customer-type="$form['type']??'individual'" /><div class="mt-6 flex gap-3"><flux:button type="submit" variant="primary" icon="check">{{ __('ui.save') }}</flux:button><flux:button wire:click="$set('creating',false)">{{ __('ui.cancel') }}</flux:button></div></form></section>@endif
@if($kind==='vehicle')
<div class="mt-7 flex flex-wrap items-center gap-3"><div class="w-full sm:w-44"><flux:select wire:model.live="status" :aria-label="__('catalog.status')"><option value="active">{{ __('catalog.active') }}</option><option value="archived">{{ __('catalog.archived') }}</option><option value="all">{{ __('catalog.all') }}</option></flux:select></div><div class="w-full sm:w-52"><flux:select wire:model.live="category" :aria-label="__('catalog.category_id')"><option value="">{{ __('catalog.all_categories') }}</option>@foreach($categories as $c)<option value="{{ $c->id }}">{{ $c->name }}</option>@endforeach</flux:select></div><span class="text-sm text-zinc-500 sm:ms-auto">{{ trans_choice('catalog.vehicle_count',$records->total(),['count'=>$records->total()]) }}</span></div>
<ul class="mt-6 grid gap-5" :class="vehicleView==='cards' ? 'sm:grid-cols-2 xl:grid-cols-3' : 'grid-cols-1'">
@forelse($records as $r)
<li wire:key="vehicle-{{ $r->id }}" class="min-w-0"><a href="{{ route('vehicles.show',$r->id) }}" class="group block h-full overflow-hidden rounded-xl border border-zinc-200 bg-white transition hover:border-zinc-400 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-teal-600 dark:border-zinc-800 dark:bg-zinc-900 dark:hover:border-zinc-600" :class="vehicleView==='list' ? 'lg:grid lg:grid-cols-[minmax(0,1.5fr)_minmax(0,2fr)_auto] lg:items-center' : ''">
<div class="flex min-w-0 items-center gap-4 p-5 xl:p-6"><span class="flex size-11 shrink-0 items-center justify-center rounded-xl bg-zinc-100 text-zinc-600 dark:bg-zinc-800 dark:text-zinc-300"><flux:icon name="car" class="size-6"/></span><div class="min-w-0"><h2 class="break-words font-semibold">{{ $r->make }} {{ $r->model }}</h2><p class="mt-1 text-sm text-zinc-500 dark:text-zinc-400"><bdi>{{ $r->registration }}</bdi> · {{ $r->year }}</p></div></div>
<dl class="grid grid-cols-2 gap-4 border-t border-zinc-100 bg-zinc-50/60 p-5 dark:border-zinc-800 dark:bg-zinc-950/20 xl:p-6" :class="vehicleView==='list' ? 'lg:border-0 lg:bg-transparent dark:lg:bg-transparent' : ''"><div class="min-w-0"><dt class="text-xs text-zinc-500 dark:text-zinc-400">{{ __('catalog.category_id') }}</dt><dd class="mt-1.5 break-words text-sm font-medium">{{ $r->category?->name ?? '—' }}</dd></div><div><dt class="text-xs text-zinc-500 dark:text-zinc-400">{{ __('catalog.mileage_km') }}</dt><dd class="mt-1.5 text-sm font-medium"><bdi>{{ number_format($r->mileage_km,0,',',' ') }}</bdi></dd></div></dl>
<div class="flex items-center justify-between gap-5 border-t border-zinc-100 p-5 dark:border-zinc-800 xl:p-6" :class="vehicleView==='list' ? 'lg:border-0' : 'bg-zinc-50/60 dark:bg-zinc-950/20'"><div><p class="text-base font-semibold"><bdi dir="ltr">{{ number_format((float)$r->daily_rate,str_ends_with($r->daily_rate,'.00')?0:2,',',' ') }} DA</bdi></p><p class="mt-1 text-xs text-zinc-500 dark:text-zinc-400">/ {{ __('catalog.day') }}</p></div><span class="inline-flex shrink-0 items-center gap-1.5 rounded-full px-3 py-1 text-xs font-medium {{ $r->archived_at?'bg-amber-100 text-amber-800 dark:bg-amber-950 dark:text-amber-300':'bg-teal-50 text-teal-800 dark:bg-teal-950 dark:text-teal-300' }}"><span class="size-1.5 rounded-full bg-current"></span>{{ __('catalog.'.($r->archived_at?'archived':'active')) }}</span><flux:icon name="chevron-right" class="size-4 shrink-0 text-zinc-400 rtl:rotate-180"/></div>
</a></li>
@empty<li class="col-span-full rounded-xl border border-dashed border-zinc-300 p-12 text-center dark:border-zinc-700"><flux:icon name="car" class="mx-auto mb-4 size-10 text-zinc-400"/><h2 class="font-semibold">{{ __('catalog.no_results') }}</h2><p class="mt-2 text-sm text-zinc-500">{{ __('catalog.empty_hint') }}</p></li>@endforelse
</ul><div class="mt-6">{{ $records->links() }}</div>
@else
<div class="mt-7 max-w-xs"><flux:select wire:model.live="status" :aria-label="__('catalog.status')">@foreach(['active','archived','all'] as $state)<option value="{{ $state }}">{{ __('catalog.'.$state) }}</option>@endforeach</flux:select></div>
<ul class="mt-6 grid gap-5" :class="directoryView==='cards' ? 'sm:grid-cols-2 xl:grid-cols-3' : 'grid-cols-1'">
@forelse($records as $r)<li wire:key="customer-{{ $r->id }}" class="min-w-0"><x-directory.entry :href="route('customers.show',$r->id)" :icon="$r->type==='company'?'building-office-2':'user'" :title="$r->name" :subtitle="__('catalog.'.$r->type).' · #'.$r->id">
<p class="text-xs text-zinc-500 dark:text-zinc-400">{{ __('catalog.phone') }}</p><p><bdi dir="ltr">{{ $r->phone ?: '—' }}</bdi></p>
<x-slot:summary><x-directory.badge :muted="(bool)$r->archived_at">{{ __('catalog.'.($r->archived_at?'archived':'active')) }}</x-directory.badge></x-slot:summary>
</x-directory.entry></li>@empty<li class="col-span-full rounded-xl border border-dashed border-zinc-300 p-12 text-center dark:border-zinc-700"><flux:icon name="users" class="mx-auto mb-4 size-10 text-zinc-400"/><h2 class="font-semibold">{{ __('catalog.no_results') }}</h2><p class="mt-2 text-sm text-zinc-500">{{ __('catalog.empty_hint') }}</p></li>@endforelse
</ul><div class="mt-6">{{ $records->links() }}</div>
@endif
</div>
