<div wire:poll.60s>
<div class="flex flex-wrap items-end justify-between gap-5"><div><p class="text-sm font-medium text-teal-700 dark:text-teal-300">{{ __('release.agency_today') }}</p><h1 class="mt-2 text-3xl font-semibold">{{ __('release.dashboard') }}</h1><p class="mt-2 text-sm text-zinc-500">{{ __('release.live_at') }} <bdi>{{ \Carbon\CarbonImmutable::parse($data['as_of'])->setTimezone('Africa/Algiers')->format('d/m/Y H:i') }}</bdi></p></div><a href="{{ route('reservations') }}" class="inline-flex items-center gap-2 rounded-xl bg-teal-700 px-4 py-3 text-sm font-medium text-white"><flux:icon name="calendar-days" class="size-5"/>{{ __('ui.reservations') }}</a></div>
<div class="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
@foreach(['total'=>'truck','available'=>'check-circle','today_pickups'=>'arrow-up-right','today_returns'=>'arrow-down-left'] as $key=>$icon)
<a href="{{ route($key==='total'?'vehicles.index':($key==='available'?'availability':($key==='today_pickups'?'reservations':'rentals'))) }}" class="rounded-2xl border border-zinc-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-900"><div class="flex justify-between gap-3"><span class="text-sm text-zinc-600 dark:text-zinc-400">{{ __('release.'.$key) }}</span><flux:icon :name="$icon" class="size-5 text-teal-600"/></div><p class="mt-3 text-3xl font-semibold tabular-nums">{{ $key==='available'?$data['fleet']['available']:$data[$key] }}</p></a>
@endforeach
</div>
<div class="mt-6 grid gap-6 xl:grid-cols-2">
<section class="rounded-2xl border border-zinc-200 bg-white p-6 dark:border-zinc-800 dark:bg-zinc-900"><h2 class="text-lg font-semibold">{{ __('release.fleet_now') }}</h2><p class="mt-1 text-sm text-zinc-500">{{ __('release.fleet_hint') }}</p><div class="mt-6 flex h-6 overflow-hidden rounded-full bg-zinc-100 dark:bg-zinc-800" aria-hidden="true">@foreach($data['fleet'] as $state=>$count)<div style="width:{{ $data['total']?100*$count/$data['total']:0 }}%;background:{{ ['rented'=>'#0f766e','maintenance'=>'#b45309','blocked'=>'#be123c','reserved'=>'#6366f1','available'=>'#65a30d'][$state] }}"></div>@endforeach</div><dl class="mt-5 space-y-3">@foreach($data['fleet'] as $state=>$count)<div class="flex justify-between gap-3"><dt class="flex items-center gap-2"><span class="size-3 rounded-full" style="background:{{ ['rented'=>'#0f766e','maintenance'=>'#b45309','blocked'=>'#be123c','reserved'=>'#6366f1','available'=>'#65a30d'][$state] }}"></span>{{ __('release.'.$state) }}</dt><dd class="font-semibold tabular-nums">{{ $count }}</dd></div>@endforeach</dl></section>
<section class="rounded-2xl border border-zinc-200 bg-white p-6 dark:border-zinc-800 dark:bg-zinc-900"><div class="flex justify-between"><h2 class="text-lg font-semibold">{{ __('release.attention') }}</h2><span class="rounded-full bg-amber-100 px-3 text-amber-900">{{ count($data['urgent']) }}</span></div><div class="mt-4 max-h-80 space-y-3 overflow-y-auto">@forelse($data['urgent'] as $item)<a href="{{ $item['url'] }}" class="block rounded-xl border border-zinc-200 p-3 hover:border-teal-500 dark:border-zinc-700"><p class="text-sm font-semibold text-amber-700 dark:text-amber-300">{{ __('release.'.$item['kind']) }}</p><p class="mt-1 break-words text-sm">{{ $item['label'] }}</p></a>@empty<p class="py-6 text-sm text-zinc-500">{{ __('release.all_clear') }}</p>@endforelse</div></section>
</div>
<form wire:submit="apply" class="my-7 flex flex-wrap items-end gap-4"><flux:input type="date" wire:model="from" :label="__('release.from')"/><flux:input type="date" wire:model="to" :label="__('release.to')"/><flux:button type="submit" icon="funnel">{{ __('release.apply') }}</flux:button></form>
@if($data['money'])
<div class="mb-6 grid gap-4 sm:grid-cols-3">@foreach(['outstanding','held','credit'] as $key)<a href="#financial-balances" class="rounded-xl border border-zinc-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-900"><p class="text-sm text-zinc-500">{{ __('release.'.$key) }}</p><p class="mt-2 text-xl font-semibold"><bdi>{{ \App\Modules\Rentals\Money::display($data['money'][$key]) }}</bdi></p></a>@endforeach</div>
<section class="rounded-2xl border border-zinc-200 bg-white p-6 dark:border-zinc-800 dark:bg-zinc-900"><h2 class="text-lg font-semibold">{{ __('release.money_trends') }}</h2><p class="mt-2 text-sm text-zinc-500">{{ __('release.money_hint') }}</p><div class="mt-4 grid gap-4 sm:grid-cols-2">@foreach(['revenue','collections'] as $key)<p>{{ __('release.'.$key) }}: <bdi class="font-semibold">{{ \App\Modules\Rentals\Money::display($data['money'][$key]) }}</bdi></p>@endforeach</div>
@php($series=$data['money']['series'])
@php($max=max(1,...array_map(fn($x)=>max(abs($x['revenue']),abs($x['collections'])),$series)))
<svg viewBox="0 0 760 220" role="img" aria-label="{{ __('release.money_trends') }}" class="mt-6 w-full text-zinc-400"><title>{{ __('release.money_trends') }}</title><line x1="10" x2="750" y1="110" y2="110" stroke="currentColor" stroke-dasharray="4 4"/>@foreach(['revenue'=>'#0f766e','collections'=>'#d97706'] as $key=>$color)<polyline fill="none" stroke="{{ $color }}" stroke-width="3" points="@foreach($series as $i=>$point){{ 10+740*$i/max(1,count($series)-1) }},{{ 110-95*$point[$key]/$max }} @endforeach"/>@endforeach</svg>
<div class="flex justify-between text-xs text-zinc-500"><bdi>{{ $data['from'] }}</bdi><bdi>{{ $data['to'] }}</bdi></div><div class="mt-3 flex flex-wrap gap-5 text-sm"><span class="text-teal-700 dark:text-teal-300">● {{ __('release.revenue') }}</span><span class="text-amber-700 dark:text-amber-300">● {{ __('release.collections') }}</span></div>
<details class="mt-4"><summary class="cursor-pointer text-sm">{{ __('release.data_table') }}</summary><div class="mt-3 max-h-80 overflow-auto"><table class="w-full text-start text-sm"><thead><tr><th class="p-2 text-start">{{ __('release.date') }}</th><th class="p-2 text-end">{{ __('release.revenue') }}</th><th class="p-2 text-end">{{ __('release.collections') }}</th></tr></thead><tbody>@foreach($series as $point)<tr class="border-t border-zinc-200 dark:border-zinc-700"><td class="p-2"><bdi>{{ $point['date'] }}</bdi></td><td class="p-2 text-end"><bdi>{{ \App\Modules\Rentals\Money::display($point['revenue']) }}</bdi></td><td class="p-2 text-end"><bdi>{{ \App\Modules\Rentals\Money::display($point['collections']) }}</bdi></td></tr>@endforeach</tbody></table></div></details></section>
<section id="financial-balances" class="mt-6 scroll-mt-28 rounded-2xl border border-zinc-200 bg-white p-6 dark:border-zinc-800 dark:bg-zinc-900"><h2 class="text-lg font-semibold">{{ __('release.balances') }}</h2><div class="mt-4 grid max-h-96 gap-3 overflow-y-auto md:grid-cols-2">@forelse($data['money']['accounts'] as $account)<a href="{{ $account['url'] }}" class="rounded-xl border border-zinc-200 p-4 dark:border-zinc-700"><p class="break-words font-medium">{{ $account['customer'] }}</p>@foreach(['outstanding','held','credit'] as $key)<p class="mt-2 flex flex-wrap justify-between gap-2 text-sm"><span>{{ __('release.'.$key) }}</span><bdi>{{ \App\Modules\Rentals\Money::display($account[$key]) }}</bdi></p>@endforeach</a>@empty<p class="text-sm text-zinc-500">{{ __('release.no_balances') }}</p>@endforelse</div></section>
@endif
<section class="mt-6 rounded-2xl border border-zinc-200 bg-white p-6 dark:border-zinc-800 dark:bg-zinc-900"><h2 class="text-lg font-semibold">{{ __('release.schedule') }}</h2><div class="mt-4 grid gap-3 md:grid-cols-2">@forelse($data['activity'] as $item)<a href="{{ $item['url'] }}" class="rounded-xl border border-zinc-200 p-4 dark:border-zinc-700"><p class="text-sm font-medium text-teal-700 dark:text-teal-300">{{ __('release.'.$item['kind']) }} · <bdi>{{ \Carbon\CarbonImmutable::parse($item['time'])->setTimezone('Africa/Algiers')->format('d/m H:i') }}</bdi></p><p class="mt-1 break-words">{{ $item['label'] }}</p></a>@empty<p class="text-sm text-zinc-500">{{ __('release.no_activity') }}</p>@endforelse</div></section>
</div>
