<div class="space-y-6"><h1 class="text-3xl font-semibold">{{ __('report.expenses') }}</h1><p class="text-sm text-zinc-500 dark:text-zinc-400">{{ __('report.expense_hint') }}</p>
@if($failure)<p role="alert" class="rounded-xl bg-red-100 p-4 text-red-900">{{ $failure }}</p>@endif
<form wire:submit="save" class="space-y-5 rounded-2xl border border-zinc-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-900"><h2 class="text-xl font-semibold">{{ __('report.record_expense') }}</h2><div class="grid gap-5 sm:grid-cols-2 lg:grid-cols-3"><flux:select wire:model="form.vehicle_id" :label="__('maintenance.vehicle')"><option value="">—</option>@foreach($vehicles as $v)<option value="{{ $v->id }}">{{ $v->registration }}</option>@endforeach
</flux:select><flux:select wire:model="form.category" :label="__('report.category')">@foreach(\App\Modules\Reporting\Expenses::CATEGORIES as $category)<option value="{{ $category }}">{{ __('report.'.$category) }}</option>@endforeach
</flux:select><flux:input type="date" wire:model="form.incurred_on" :label="__('report.incurred_on')"/><flux:input wire:model="form.amount" inputmode="decimal" :label="__('report.amount')"/></div><flux:textarea wire:model="form.description" :label="__('report.description')" rows="2"/><flux:button type="submit" variant="primary" icon="plus">{{ __('ui.save') }}</flux:button></form>
<div class="max-w-sm"><flux:select wire:model.live="vehicle_id" :label="__('maintenance.filter')"><option value="">{{ __('maintenance.all') }}</option>@foreach($vehicles as $v)<option value="{{ $v->id }}">{{ $v->registration }}</option>@endforeach
</flux:select></div><div class="grid gap-4 lg:grid-cols-2">@forelse($records as $r)<article class="min-w-0 rounded-2xl border border-zinc-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-900"><div class="flex flex-wrap justify-between gap-3"><h2 class="font-semibold">{{ $r->vehicle->registration }} · {{ __('report.'.$r->category) }} #{{ $r->id }}</h2><bdi>{{ \App\Modules\Rentals\Money::display($r->amount_cents) }}</bdi></div><p class="mt-2 text-sm">{{ $r->incurred_on->format('Y-m-d') }}</p><p class="mt-3 whitespace-pre-wrap break-words">{{ $r->description }}</p>
@if($r->maintenance_record_id)<a class="mt-3 block text-sm underline" href="{{ route('maintenance',['vehicle_id'=>$r->vehicle_id]) }}#service-{{ $r->maintenance_record_id }}">{{ __('report.linked_service') }} #{{ $r->maintenance_record_id }}</a>@endif
@if($r->reverses_id)<p class="mt-3">{{ __('report.reverses') }} #{{ $r->reverses_id }}</p>@elseif($r->reversal)<p class="mt-3">{{ __('report.reversed') }} #{{ $r->reversal->id }}</p>@else<flux:button class="mt-3" wire:click="reverse({{ $r->id }})" icon="arrow-uturn-left">{{ __('report.reverse') }}</flux:button>@endif
<div class="mt-3 flex flex-wrap gap-3">@foreach($r->attachments as $a)<a class="text-sm underline" href="{{ route('expense-attachments.download',$a->id) }}">{{ __('maintenance.attachment') }} #{{ $a->id }}</a>@endforeach
</div></article>@empty<p>{{ __('report.no_expenses') }}</p>@endforelse
</div>{{ $records->links() }}<div class="grid gap-5 lg:grid-cols-2"><form wire:submit="upload" class="space-y-4 rounded-2xl border border-zinc-200 p-5 dark:border-zinc-800"><flux:select wire:model="attachmentExpense" :label="__('report.select_expense')"><option value="">—</option>@foreach($records as $r)<option value="{{ $r->id }}">{{ $r->vehicle->registration }} · {{ $r->incurred_on->format('Y-m-d') }} #{{ $r->id }}</option>@endforeach
</flux:select><flux:input type="file" wire:model="file" accept="application/pdf,image/jpeg,image/png" :label="__('maintenance.attachment')"/><flux:button type="submit">{{ __('ui.save') }}</flux:button></form><div class="space-y-3 rounded-2xl border border-zinc-200 p-5 dark:border-zinc-800"><flux:textarea wire:model="reason" :label="__('report.reversal_reason')" rows="2"/><p class="text-sm">{{ __('report.reversal_hint') }}</p></div></div></div>
