<div class="mt-8"><h2 class="text-xl font-semibold">{{ __('rental.finances') }}</h2><p class="mt-2 text-sm text-zinc-500">{{ __('rental.ledger_hint') }}</p>
<div class="my-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5">@foreach(['charges_cents','payments_cents','outstanding_cents','held_cents','credit_cents'] as $metric)<div class="rounded-xl border border-zinc-200 bg-white p-4 dark:border-zinc-800 dark:bg-zinc-900"><p class="text-xs text-zinc-500">{{ __('rental.'.$metric) }}</p><p class="mt-2 font-semibold"><bdi>{{ \App\Modules\Rentals\Money::display($totals[$metric]) }}</bdi></p></div>@endforeach</div>
@if($failure)<p role="alert" class="mb-4 rounded-lg bg-red-100 p-4 text-red-900 dark:bg-red-950 dark:text-red-100">{{ $failure }}</p>@endif
@can('payments.collect')<form wire:submit="postEntry" class="rounded-2xl border border-zinc-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-900"><div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
<flux:select wire:model.live="form.kind" :label="__('rental.entry_kind')">@foreach(\App\Modules\Rentals\Ledger::KINDS  as $kind)@if(!in_array($kind,['refund','deposit_applied','deposit_refunded','reversal'])||auth()->user()->can('finance.manage'))<option value="{{ $kind }}">{{ __('rental.'.$kind) }}</option>@endif @endforeach</flux:select>
@if($form['kind']!=='reversal')<flux:input wire:model="form.amount" type="number" min="0.01" step="0.01" :label="__('rental.amount')"/>@else<flux:select wire:model="form.reverses_id" :label="__('rental.original_entry')"><option value="">—</option>@foreach($entries  as $entry)@if($entry->kind!=='reversal'&&$entry->category!=='base'&&!$entries->contains('reverses_id',$entry->id))<option value="{{ $entry->id }}">#{{ $entry->id }} · {{ __('rental.'.$entry->kind) }} · {{ \App\Modules\Rentals\Money::display($entry->amount_cents) }}</option>@endif @endforeach</flux:select>@endif
@if($form['kind']==='charge')<flux:select wire:model="form.category" :label="__('rental.charge_category')">@foreach(['late','fuel','damage','mileage','towing','cancellation','other'] as $c)<option value="{{ $c }}">{{ __('rental.'.$c) }}</option>@endforeach</flux:select>@endif
@if(in_array($form['kind'],['payment','refund','deposit_received','deposit_refunded']))<flux:select wire:model="form.method" :label="__('rental.method')">@foreach(\App\Modules\Rentals\Ledger::METHODS  as $m)<option value="{{ $m }}">{{ __('rental.'.$m) }}</option>@endforeach</flux:select><flux:input wire:model="form.reference" :label="__('rental.reference')"/>@endif
<flux:input wire:model="form.effective_at" type="datetime-local" :label="__('rental.effective_at')"/>
</div><div class="mt-4"><flux:input wire:model="form.reason" :label="__('booking.reason')"/></div><flux:button class="mt-5" type="submit" variant="primary" icon="banknotes" wire:loading.attr="disabled">{{ __('rental.post_entry') }}</flux:button></form>@endcan
<div class="mt-5 space-y-3">@forelse($entries  as $entry)<article class="rounded-xl border border-zinc-200 p-4 dark:border-zinc-800"><div class="flex flex-wrap justify-between gap-2"><h3 class="font-medium">#{{ $entry->id }} · {{ __('rental.'.$entry->kind) }} @if($entry->category) · {{ __('rental.'.$entry->category) }}@endif</h3><bdi>{{ \App\Modules\Rentals\Money::display($entry->amount_cents) }}</bdi></div><p class="mt-2 text-sm">{{ $entry->reason }}@if($entry->reverses_id) · {{ __('rental.original_entry') }} #{{ $entry->reverses_id }}@endif</p><p class="mt-2 text-xs text-zinc-500"><bdi>{{ $entry->effective_at->setTimezone('Africa/Algiers')->format('d/m/Y H:i') }}</bdi>@if($entry->method) · {{ __('rental.'.$entry->method) }}@endif @if($entry->reference) · {{ $entry->reference }}@endif</p></article>@empty<p class="text-sm text-zinc-500">{{ __('booking.empty') }}</p>@endforelse</div></div>
