<div>
<a href="{{ route('rentals') }}" class="text-sm text-teal-700 dark:text-teal-300">{{ __('rental.rentals') }}</a><div class="my-5 flex flex-wrap justify-between gap-3"><h1 class="text-2xl font-semibold">{{ __('rental.rental') }} #{{ $id }} · {{ $record->vehicle->registration }}</h1><span>{{ __('rental.'.$record->status) }}</span></div>
@if($failure)<p role="alert" class="mb-5 rounded-lg bg-red-100 p-4 text-red-900 dark:bg-red-950 dark:text-red-100">{{ $failure }}</p>@endif
@if($record->status==='active'&&$record->ends_at->isPast())<p class="mb-5 rounded-lg bg-red-100 p-4 text-red-900 dark:bg-red-950 dark:text-red-100">{{ __('rental.overdue_hint') }}</p>@endif
<div class="grid gap-4 lg:grid-cols-2"><section class="rounded-2xl border border-zinc-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-900"><h2 class="font-semibold">{{ __('rental.agreement') }} · {{ __('rental.version') }} {{ $record->contract_version }}</h2><p class="mt-3"><a href="{{ route('customers.show',$record->customer_id) }}" class="text-teal-700 dark:text-teal-300">{{ $record->snapshot['customer']['name'] }}</a></p><p>{{ __('rental.driver') }}: {{ $record->snapshot['driver']['name'] ?? '—' }}</p>@if($record->driver_id)<a class="text-sm text-teal-700 dark:text-teal-300" href="{{ route('customers.show',$record->driver_id) }}">{{ __('rental.driver_profile') }}</a>@endif<p class="mt-3 text-sm"><bdi>{{ $record->starts_at->setTimezone('Africa/Algiers')->format('d/m/Y H:i') }} → {{ $record->ends_at->setTimezone('Africa/Algiers')->format('d/m/Y H:i') }}</bdi></p><p class="mt-2 text-sm">{{ __('booking.buffer') }}: {{ $record->preparation_minutes }} {{ __('booking.minutes') }}</p><p class="mt-2 text-sm">{{ __('rental.mileage_allowance') }}: {{ $record->mileage_allowance ?? __('rental.unlimited') }}</p><p class="mt-2 whitespace-pre-wrap break-words text-sm">{{ $record->terms }}</p></section>
<section class="rounded-2xl border border-zinc-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-900"><h2 class="font-semibold">{{ __('rental.pricing') }}</h2><p class="mt-3">{{ __('rental.'.$record->pricing['basis']) }} × {{ $record->pricing['quantity'] }}</p>@foreach(['base_cents','discount_cents','total_cents'] as $key)<p class="mt-3 flex flex-wrap justify-between gap-2"><span>{{ __('rental.'.$key) }}</span><bdi>{{ \App\Modules\Rentals\Money::display($record->pricing[$key]) }}</bdi></p>@endforeach<p class="mt-3 text-xs text-zinc-500">{{ __('rental.no_auto_charge') }}</p></section></div>
@can('rentals.manage')@if(in_array($record->status,['draft','active']))
<section class="mt-6 rounded-2xl border border-zinc-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-900"><h2 class="mb-4 text-xl font-semibold">{{ __('rental.'.($record->status==='draft'?'handover':'return')) }}</h2><form wire:submit="inspect('{{ $record->status==='draft'?'handover':'return' }}')" class="space-y-4"><div class="grid gap-4 sm:grid-cols-3"><flux:input type="datetime-local" wire:model="form.occurred_at" :label="__('rental.occurred_at')"/><flux:input type="number" min="0" wire:model="form.mileage_km" :label="__('catalog.mileage_km')"/><flux:input type="number" min="0" max="100" wire:model="form.fuel_percent" :label="__('rental.fuel_percent')"/></div>@if($record->status==='draft' && $record->customer->type==='company')<flux:select wire:model="form.driver_id" :label="__('rental.driver')"><option value="">—</option>@foreach($drivers as $driver)<option value="{{ $driver->id }}">{{ $driver->name }}</option>@endforeach</flux:select>@endif
<flux:textarea wire:model="form.condition_notes"  :label="__('rental.condition_notes')" rows="2"/><flux:checkbox wire:model="form.condition_confirmed" :label="__('rental.condition_confirmed')"/>
@if($record->status==='draft')@can('vehicle-documents.override')<flux:input wire:model="form.document_override_reason" :label="__('booking.override_reason')"/>@endcan @else @can('pricing.override')<flux:input wire:model="form.correction_reason" :label="__('rental.correction_reason')"/>@endcan @endif
<flux:button type="submit" variant="primary" icon="check" wire:loading.attr="disabled">{{ __('rental.'.($record->status==='draft'?'handover':'return')) }}</flux:button></form></section>
<details class="mt-6 rounded-2xl border border-zinc-200 p-5 dark:border-zinc-800"><summary class="cursor-pointer font-semibold">{{ __('rental.extend') }}</summary><form wire:submit="extendRental" class="mt-4 space-y-4"><flux:input type="datetime-local" wire:model="extension.ends_at" :label="__('booking.ends_at')"/><x-rental-pricing prefix="extension"/><flux:input wire:model="extension.reason" :label="__('booking.reason')"/>@can('vehicle-documents.override')<flux:input wire:model="extension.document_override_reason" :label="__('booking.override_reason')"/>@endcan<flux:button type="submit" variant="primary" wire:loading.attr="disabled">{{ __('rental.extend') }}</flux:button></form></details>
@if($record->status==='draft')<details class="mt-5 rounded-xl border border-zinc-200 p-5 dark:border-zinc-800"><summary class="cursor-pointer font-semibold">{{ __('rental.cancel_draft') }}</summary><p class="my-3 text-sm text-zinc-500">{{ __('rental.cancel_hint') }}</p><flux:input wire:model="reason" :label="__('booking.reason')"/><flux:button class="mt-4" wire:click="cancelRental" wire:confirm="{{ __('rental.cancel_confirm') }}" variant="danger" wire:loading.attr="disabled">{{ __('rental.cancel_draft') }}</flux:button></details>@endif
@endif @endcan
@if($record->inspections->isNotEmpty())<section class="mt-8"><h2 class="mb-4 text-xl font-semibold">{{ __('rental.inspections') }}</h2><div class="grid gap-4 md:grid-cols-2">@foreach($record->inspections  as $inspection)<article class="rounded-xl border border-zinc-200 p-5 dark:border-zinc-800"><h3 class="font-semibold">{{ __('rental.'.$inspection->kind) }} · <bdi>{{ $inspection->occurred_at->setTimezone('Africa/Algiers')->format('d/m/Y H:i') }}</bdi></h3><p class="mt-2 text-sm">{{ $inspection->mileage_km }} km · {{ __('rental.fuel_percent') }}: {{ $inspection->fuel_percent }}%</p><p class="mt-2 whitespace-pre-wrap break-words text-sm">{{ $inspection->condition_notes }}</p>@can('rentals.manage')@foreach($inspection->photos  as $photo)<a class="mt-3 block text-sm text-teal-700 dark:text-teal-300" href="{{ route('inspection-photos.download',$photo->id) }}">{{ __('rental.photo') }} #{{ $photo->id }}</a>@endforeach @endcan</article>@endforeach</div>@can('rentals.manage')<form wire:submit="addPhoto" class="mt-5 space-y-4 rounded-xl border border-zinc-200 p-5 dark:border-zinc-800"><flux:select wire:model="inspectionId" :label="__('rental.inspection')"><option value="">—</option>@foreach($record->inspections  as $inspection)<option value="{{ $inspection->id }}">{{ __('rental.'.$inspection->kind) }}</option>@endforeach</flux:select><flux:input wire:model="photo" type="file" accept="image/jpeg,image/png" :label="__('rental.photo')"/><div class="sm:hidden"><flux:input wire:model="photo" type="file" accept="image/jpeg,image/png" capture="environment" :label="__('catalog.take_photo')"/></div>@error('file')<p class="text-sm text-red-600">{{ $message }}</p>@enderror<flux:button type="submit" icon="arrow-up-tray" wire:loading.attr="disabled">{{ __('rental.add_photo') }}</flux:button></form>@endcan</section>@endif
<livewire:ledger-panel owner="rental" :owner-id="$id" :key="'rental-ledger-'.$id" />
<details class="mt-8 rounded-xl border border-zinc-200 p-5 dark:border-zinc-800"><summary class="cursor-pointer font-semibold">{{ __('rental.agreement_history') }}</summary>@foreach($versions  as $version)@php($snapshot=json_decode($version->snapshot,true))<article class="mt-4 border-t border-zinc-200 pt-4 dark:border-zinc-700"><h3 class="font-medium">{{ __('rental.version') }} {{ $version->number }} · {{ $snapshot['parties']['customer']['name'] }}</h3><p class="mt-2 text-sm">{{ $version->reason }}</p><p class="mt-2 text-sm"><bdi>{{ \Carbon\CarbonImmutable::parse($snapshot['starts_at'])->setTimezone('Africa/Algiers')->format('d/m/Y H:i') }} → {{ \Carbon\CarbonImmutable::parse($snapshot['ends_at'])->setTimezone('Africa/Algiers')->format('d/m/Y H:i') }}</bdi> · <bdi>{{ \App\Modules\Rentals\Money::display($snapshot['pricing']['total_cents']) }}</bdi></p></article>@endforeach</details>
</div>
