<div class="space-y-6"><h1 class="text-3xl font-semibold">{{ __('report.reports') }}</h1><p class="text-sm text-zinc-500 dark:text-zinc-400">{{ __('report.report_hint') }}</p>
<form wire:submit="apply" class="flex flex-wrap items-end gap-4"><flux:input type="date" wire:model="from" :label="__('release.from')"/><flux:input type="date" wire:model="to" :label="__('release.to')"/><flux:select wire:model="vehicle_id" :label="__('maintenance.vehicle')"><option value="">{{ __('maintenance.all') }}</option>@foreach($vehicles as $v)<option value="{{ $v->id }}">{{ $v->registration }}</option>@endforeach
</flux:select><flux:button type="submit" variant="primary">{{ __('release.apply') }}</flux:button><flux:button href="{{ route('reports.export',$period) }}" icon="arrow-down-tray">{{ __('report.export') }}</flux:button></form>
<p class="text-sm"><bdi dir="ltr">{{ $data['from'] }} → {{ $data['to'] }}</bdi></p><div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">@foreach(['revenue','collections','expenses','contribution','rental_count'] as $metric)<div class="rounded-2xl border border-zinc-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-900"><h2 class="text-sm">{{ __('report.'.$metric) }}</h2><p class="mt-3 break-words text-2xl font-semibold"><bdi>{{ $metric==='rental_count'?$data['totals'][$metric]:\App\Modules\Rentals\Money::display($data['totals'][$metric]) }}</bdi></p></div>@endforeach
</div><p class="text-sm">{{ __('report.cancellation') }}: <bdi>{{ \App\Modules\Rentals\Money::display($data['totals']['standalone_cancellation']) }}</bdi></p>
<section class="rounded-2xl border border-zinc-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-900"><h2 class="text-xl font-semibold">{{ __('report.expense_categories') }}</h2><div class="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">@foreach($data['categories'] as $category=>$amount)<div><div class="flex justify-between gap-2 text-sm"><span>{{ __('report.'.$category) }}</span><bdi>{{ \App\Modules\Rentals\Money::display($amount) }}</bdi></div><div class="mt-2 h-2 rounded bg-zinc-100 dark:bg-zinc-800" aria-hidden="true"><div class="h-2 rounded bg-teal-600" style="width:{{ $data['totals']['expenses']>0?max(0,min(100,100*$amount/$data['totals']['expenses'])):0 }}%"></div></div></div>@endforeach
</div></section>
<section class="rounded-2xl border border-zinc-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-900"><h2 class="text-xl font-semibold">{{ __('report.most_rented') }}</h2><ol class="mt-4 space-y-3">@foreach(collect($data['vehicles'])->where('rental_count','>',0)->sortByDesc('rental_count')->take(5) as $leader)<li class="flex justify-between gap-4"><a class="text-teal-700 dark:text-teal-300" href="{{ route('vehicles.show',$leader['vehicle_id']) }}">{{ $leader['registration'] }}</a><span>{{ $leader['rental_count'] }}</span></li>@endforeach
</ol></section>
<section><h2 class="text-xl font-semibold">{{ __('report.by_vehicle') }}</h2><p class="my-3 text-sm">{{ __('report.utilization_hint') }}</p><div class="grid gap-4 lg:grid-cols-2">@foreach($data['vehicles'] as $row)<article class="min-w-0 rounded-2xl border border-zinc-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-900"><a href="{{ route('vehicles.show',$row['vehicle_id']) }}" class="font-semibold text-teal-700 dark:text-teal-300">{{ $row['registration'] }}</a><dl class="mt-4 space-y-2">@foreach(['revenue','collections','expenses','maintenance_cost','contribution','rental_count','rented_hours','eligible_hours','utilization'] as $metric)<div class="flex flex-wrap justify-between gap-2 text-sm"><dt>{{ __('report.'.$metric) }}</dt><dd><bdi>{{ $row[$metric]===null?__('report.na'):(in_array($metric,['revenue','collections','expenses','maintenance_cost','contribution'])?\App\Modules\Rentals\Money::display($row[$metric]):$row[$metric].($metric==='utilization'?'%':'')) }}</bdi></dd></div>@endforeach
</dl>@if($row['utilization_status']!=='ok')<p class="mt-4 text-sm text-amber-700 dark:text-amber-300">{{ __('report.'.$row['utilization_status']) }}</p>@endif
</article>@endforeach
</div></section><p class="text-sm">{{ __('report.unallocated') }}: {{ __('report.revenue') }} <bdi>{{ \App\Modules\Rentals\Money::display($data['unallocated']['revenue']) }}</bdi> · {{ __('report.collections') }} <bdi>{{ \App\Modules\Rentals\Money::display($data['unallocated']['collections']) }}</bdi></p>
<details class="rounded-2xl border border-zinc-200 p-5 dark:border-zinc-800"><summary class="cursor-pointer font-semibold">{{ __('report.daily') }}</summary><div class="mt-4 max-h-96 overflow-auto"><table class="w-full text-sm"><thead><tr><th class="p-2 text-start">{{ __('release.date') }}</th>@foreach(['revenue','collections','expenses'] as $metric)<th class="p-2 text-end">{{ __('report.'.$metric) }}</th>@endforeach
</tr></thead><tbody>@foreach($data['daily'] as $day)<tr class="border-t border-zinc-200 dark:border-zinc-800"><td class="p-2"><bdi>{{ $day['date'] }}</bdi></td>@foreach(['revenue','collections','expenses'] as $metric)<td class="p-2 text-end"><bdi>{{ \App\Modules\Rentals\Money::display($day[$metric]) }}</bdi></td>@endforeach
</tr>@endforeach
</tbody></table></div></details></div>
