<div>
<div class="flex flex-wrap items-center justify-between gap-4"><div><p class="text-sm text-teal-700 dark:text-teal-300">{{ __('booking.timezone') }}</p><h1 class="mt-2 text-3xl font-semibold">{{ __('booking.reservations') }}</h1></div><div class="flex gap-3"><flux:button :href="route('availability')" icon="magnifying-glass">{{ __('booking.availability') }}</flux:button>@can('reservations.manage')<flux:modal.trigger name="new-reservation"><flux:button variant="primary" icon="plus">{{ __('booking.new') }}</flux:button></flux:modal.trigger>@endcan</div></div>
@can('reservations.manage')<flux:modal name="new-reservation" class="w-full max-w-3xl"><livewire:reservation-editor /></flux:modal>@endcan
<div class="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><flux:select wire:model.live="mode" :label="__('booking.view')"><option value="list">{{ __('booking.list') }}</option><option value="calendar">{{ __('booking.calendar') }}</option></flux:select><flux:select wire:model.live="status" :label="__('booking.status')"><option value="">{{ __('booking.all') }}</option>@foreach(['tentative','confirmed','cancelled','converted'] as $s)<option value="{{ $s }}">{{ __('booking.'.$s) }}</option>@endforeach</flux:select>@if($mode==='list')<flux:input type="date" wire:model.live="from" :label="__('booking.from')"/><flux:input type="date" wire:model.live="to" :label="__('booking.to')"/>@else<flux:input type="date" wire:model.live="week" :label="__('booking.week')"/>@endif</div>
@if($mode==='calendar')
<div class="my-5 flex justify-between gap-3"><flux:button wire:click="shiftWeek(-1)">{{ __('booking.previous') }}</flux:button><flux:button wire:click="shiftWeek(1)">{{ __('booking.next') }}</flux:button></div>
<div class="grid gap-3 md:grid-cols-2 xl:grid-cols-7">@foreach($days as $day)<section class="min-w-0 rounded-xl border border-zinc-200 bg-white p-3 dark:border-zinc-800 dark:bg-zinc-900"><h2 class="mb-4 font-semibold">{{ $day->locale(app()->getLocale())->translatedFormat('D d/m') }}</h2>
@foreach($records as $r)@if($r->status!=='converted'&&$r->starts_at->lt($day->addDay())&&$r->ends_at->addMinutes($r->preparation_minutes)->gt($day))<a href="{{ route('reservations.show',$r->id) }}" class="mb-3 block break-words rounded-lg border-s-4 {{ $r->status==='confirmed'?'border-teal-500':'border-zinc-400' }} bg-stone-100 p-3 text-sm dark:bg-zinc-800"><strong>#{{ $r->id }} · {{ $r->customer->name }}</strong><p>{{ $r->vehicle?->registration ?? $r->category?->name }}</p><p>{{ __('booking.'.$r->status) }}</p><p><bdi>{{ $r->starts_at->setTimezone('Africa/Algiers')->format('d/m H:i') }} → {{ $r->ends_at->setTimezone('Africa/Algiers')->format('d/m H:i') }}</bdi></p>@if($a->affected($r)->isNotEmpty())<p class="text-red-700 dark:text-red-300">{{ __('booking.affected') }}</p>@endif</a>@endif @endforeach
@foreach($rentals as $rental)@if($rental->starts_at->lt($day->addDay())&&($rental->ends_at->addMinutes($rental->preparation_minutes)->gt($day)||($rental->status==='active'&&$rental->ends_at->isPast())))<a href="{{ route('rentals.show',$rental->id) }}" class="mb-3 block break-words rounded-lg border-s-4 border-blue-500 bg-blue-50 p-3 text-sm dark:bg-blue-950"><strong>{{ __('rental.rental') }} #{{ $rental->id }}</strong><p>{{ $rental->customer->name }} · {{ $rental->vehicle->registration }}</p><p>{{ __('rental.'.$rental->status) }}</p>@if($rental->status==='active'&&$rental->ends_at->isPast())<p class="text-red-700 dark:text-red-300">{{ __('rental.overdue') }}</p>@endif</a>@endif @endforeach
@foreach($blocks as $block)@if($block->starts_at->lt($day->addDay())&&(!$block->ends_at||$block->ends_at->gt($day)))<a href="{{ route('availability') }}" class="mb-3 block rounded-lg bg-amber-100 p-3 text-sm text-amber-950 dark:bg-amber-950 dark:text-amber-100">{{ $block->vehicle->registration }} · {{ __('booking.'.$block->kind) }}<p>{{ $block->ends_at?->setTimezone('Africa/Algiers')->format('d/m H:i') ?? __('booking.indefinite') }}</p></a>@endif @endforeach
</section>@endforeach</div>
@else
<div class="mt-6 space-y-3">@forelse($records as $r)<a href="{{ route('reservations.show',$r->id) }}" class="block rounded-2xl border border-zinc-200 bg-white p-5 hover:border-teal-500 dark:border-zinc-800 dark:bg-zinc-900"><div class="flex flex-wrap justify-between gap-3"><h2 class="font-semibold">#{{ $r->id }} · {{ $r->customer->name }}</h2><span class="text-sm">{{ __('booking.'.$r->status) }}</span></div><p class="mt-2 text-sm">{{ $r->vehicle?->registration ?? $r->category?->name ?? '—' }} · <bdi>{{ $r->starts_at->setTimezone('Africa/Algiers')->format('d/m/Y H:i') }} → {{ $r->ends_at->setTimezone('Africa/Algiers')->format('d/m/Y H:i') }}</bdi></p>@if($pickup=$a->pickupStatus($r))<p class="mt-2 font-medium text-amber-700 dark:text-amber-300">{{ __('booking.'.$pickup) }}</p>@endif @if($a->affected($r)->isNotEmpty())<p class="mt-2 font-medium text-red-700 dark:text-red-300">{{ __('booking.affected') }}</p>@endif</a>@empty<p class="rounded-xl border border-dashed p-8 text-center">{{ __('booking.empty') }}</p>@endforelse</div><div class="mt-6">{{ $records->links() }}</div>
@endif
</div>
