@extends('print.layout')
@section('title','CON-'.$id.'-V'.$version)
@section('document')
@php($template=$snapshot['template'])
@if($template['sample'])<p class="sample">MODÈLE — NON VALIDÉ POUR USAGE RÉEL<br><span lang="ar" dir="rtl">نموذج — غير معتمد للاستخدام الفعلي</span></p>@endif
<header><h1>Contrat de location <span lang="ar" dir="rtl">عقد تأجير مركبة</span></h1><p><bdi>CON-{{ $id }}-V{{ $version }}</bdi></p><strong>{{ $template['agency']['name'] }}</strong><p class="muted">{{ $template['agency']['address'] }} · <bdi>{{ $template['agency']['phone'] }}</bdi><br>{{ $template['agency']['identifier'] }}</p></header>
<div class="columns"><section><h2>Locataire / <span lang="ar" dir="rtl">المستأجر</span></h2>@foreach(['name'=>'Nom / الاسم','address'=>'Adresse / العنوان','phone'=>'Téléphone / الهاتف','contact_person'=>'Contact société / ممثل الشركة'] as $key=>$label)<div class="field"><div class="label">{{ $label }}</div><div class="value">{{ $snapshot['parties']['customer'][$key]??'—' }}</div></div>@endforeach</section><section><h2>Conducteur / <span lang="ar" dir="rtl">السائق</span></h2>@foreach(['name'=>'Nom / الاسم','birth_date'=>'Naissance / تاريخ الميلاد','identity_number'=>'Identité / رقم الهوية','identity_issue_date'=>'Délivrance identité / إصدار الهوية','identity_expiry_date'=>'Expiration identité / انتهاء الهوية','licence_number'=>'Permis / رخصة السياقة','licence_country'=>'Pays / البلد','licence_issue_date'=>'Délivrance permis / إصدار الرخصة','licence_expiry_date'=>'Expiration / تاريخ الانتهاء'] as $key=>$label)<div class="field"><div class="label">{{ $label }}</div><div class="value"><bdi>{{ !empty($snapshot['parties']['driver'][$key]) && str_ends_with($key,'date') ? \Carbon\CarbonImmutable::parse($snapshot['parties']['driver'][$key])->format('d/m/Y') : ($snapshot['parties']['driver'][$key]??'—') }}</bdi></div></div>@endforeach</section></div>
<h2>Véhicule et période / <span lang="ar" dir="rtl">المركبة والمدة</span></h2><p><bdi>{{ $snapshot['parties']['vehicle']['registration'] }} · {{ $snapshot['parties']['vehicle']['make'] }} {{ $snapshot['parties']['vehicle']['model'] }}</bdi></p><p><bdi>{{ \Carbon\CarbonImmutable::parse($snapshot['starts_at'])->setTimezone('Africa/Algiers')->format('d/m/Y H:i') }} → {{ \Carbon\CarbonImmutable::parse($snapshot['ends_at'])->setTimezone('Africa/Algiers')->format('d/m/Y H:i') }}</bdi> (Africa/Algiers)</p>
<p class="muted">{{ __('rental.'.$snapshot['pricing']['basis'],[],'fr') }} / <span dir="rtl" lang="ar">{{ __('rental.'.$snapshot['pricing']['basis'],[],'ar') }}</span> × {{ $snapshot['pricing']['quantity'] }}</p><table><tbody><tr><th>Base / السعر الأساسي</th><td><bdi>{{ \App\Modules\Rentals\Money::display($snapshot['pricing']['base_cents']) }}</bdi></td></tr><tr><th>Remise / التخفيض</th><td><bdi>{{ \App\Modules\Rentals\Money::display($snapshot['pricing']['discount_cents']) }}</bdi></td></tr><tr><th>Total convenu / المبلغ المتفق عليه</th><td><bdi>{{ \App\Modules\Rentals\Money::display($snapshot['pricing']['total_cents']) }}</bdi></td></tr><tr><th>Kilométrage inclus / المسافة المشمولة</th><td>{{ $snapshot['mileage_allowance']??'Illimité / غير محدودة' }}</td></tr></tbody></table>
<div class="terms">{{ $snapshot['terms'] }}</div>
<section class="columns"><p class="terms">{{ $template['terms_fr'] }}</p><p class="terms" lang="ar" dir="rtl">{{ $template['terms_ar'] }}</p></section>
<div class="signatures"><div class="signature">Signature client / conducteur<br><span lang="ar" dir="rtl">توقيع المستأجر / السائق</span></div><div class="signature">Signature représentant de l’agence<br><span lang="ar" dir="rtl">توقيع ممثل الوكالة</span></div></div>
<p class="muted">Version {{ $version }} · {{ \Carbon\CarbonImmutable::parse($created_at)->setTimezone('Africa/Algiers')->format('d/m/Y H:i') }} · Signature manuscrite / توقيع يدوي</p>
@endsection
