<?php

return ['required' => 'الحقل :attribute مطلوب.', 'email' => 'قيمة :attribute غير صالحة.', 'unique' => 'قيمة :attribute غير صالحة.', 'in' => 'قيمة :attribute غير صالحة.', 'boolean' => 'قيمة :attribute غير صالحة.', 'integer' => 'قيمة :attribute غير صالحة.', 'string' => 'قيمة :attribute غير صالحة.', 'confirmed' => 'قيمة :attribute غير صالحة.', 'min' => ['string' => 'يجب أن يحتوي :attribute على :min أحرف على الأقل.', 'numeric' => 'قيمة :attribute غير صالحة.'], 'max' => [
    'file' => 'قيمة :attribute غير صالحة.', 'string' => 'قيمة :attribute غير صالحة.', 'numeric' => 'قيمة :attribute غير صالحة.'], 'attributes' => [
        ...(require __DIR__.'/catalog.php'), 'brand' => 'وكالة التأجير', 'workspace' => 'مساحة الوكالة', 'dashboard' => 'الرئيسية', 'preferences' => 'التفضيلات', 'staff' => 'الفريق', 'settings' => 'الإعدادات', 'audit' => 'سجل الإجراءات', 'login' => 'تسجيل الدخول', 'logout' => 'تسجيل الخروج', 'email' => 'البريد الإلكتروني', 'password' => 'كلمة المرور', 'current_password' => 'كلمة المرور الحالية', 'password_confirmation' => 'تأكيد كلمة المرور', 'locale' => 'اللغة', 'theme' => 'المظهر', 'light' => 'فاتح', 'dark' => 'داكن', 'system' => 'النظام', 'save' => 'حفظ التغييرات', 'saved' => 'تم حفظ التغييرات.', 'name' => 'الاسم الكامل', 'role' => 'الدور', 'manager' => 'المدير', 'agent' => 'موظف التأجير', 'finance' => 'الصندوق / المالية', 'active' => 'حساب نشط', 'inactive' => 'هذا الحساب معطل.', 'reason' => 'السبب', 'edit' => 'تعديل', 'new_staff' => 'إضافة موظف', 'cancel' => 'إلغاء', 'temporary_password' => 'كلمة مرور مؤقتة (12 حرفًا على الأقل)', 'reset_hint' => 'اتركه فارغًا للاحتفاظ بكلمة المرور الحالية.', 'change_password' => 'تغيير كلمة المرور', 'change_required' => 'اختر كلمة مرور جديدة للمتابعة.', 'invalid_login' => 'بيانات الدخول غير صحيحة أو الحساب معطل.', 'throttled' => 'محاولات كثيرة. أعد المحاولة بعد دقيقة.', 'invalid_password' => 'كلمة المرور الحالية غير صحيحة.', 'different_password' => 'اختر كلمة مرور مختلفة.', 'last_manager' => 'يجب الإبقاء على مدير نشط واحد على الأقل.', 'self_change' => 'لا يمكنك تعطيل حسابك أو تخفيض صلاحياته.', 'preparation_minutes' => 'التحضير بين الإيجارات (دقائق)', 'late_grace_minutes' => 'مهلة التأخير (دقائق)', 'no_show_minutes' => 'مهلة تنبيه عدم الحضور (دقائق)', 'upload_limit_mb' => 'حد حجم الملف (ميغابايت، أقصى 10)', 'empty_audit' => 'لا توجد إجراءات مسجلة بعد.', 'details' => 'التفاصيل', 'before' => 'قبل', 'after' => 'بعد', 'system_actor' => 'النظام', 'menu' => 'القائمة', 'skip' => 'انتقل إلى المحتوى', 'welcome' => 'وكالتك في مكان واحد.', 'intro' => 'أدر صلاحيات فريقك وجهّز مساحة العمل.', 'phase' => 'الإعداد الأولي', 'later' => 'ستتم إضافة المركبات والعملاء والإيجارات في المراحل القادمة.', 'team_hint' => 'حسابات فردية وأدوار ووصول آمن.', 'preferences_hint' => 'لغتك وتفضيلات العرض.', 'settings_hint' => 'الإعدادات المشتركة لوكالتك.', 'audit_hint' => 'سجل للتغييرات المهمة.', 'login_hint' => 'سجّل الدخول بحساب الموظف.', 'recovery_hint' => 'تحتاج إلى الوصول؟ تواصل مع مديرك.'],    'numeric' => 'قيمة :attribute غير صالحة.',
    'date' => 'قيمة :attribute غير صالحة.',
    'date_format' => 'قيمة :attribute غير صالحة.',
    'before_or_equal' => 'قيمة :attribute غير صالحة.',
    'after_or_equal' => 'قيمة :attribute غير صالحة.',
    'exists' => 'قيمة :attribute غير صالحة.',
    'decimal' => 'قيمة :attribute غير صالحة.',
    'file' => 'قيمة :attribute غير صالحة.',
    'mimes' => 'قيمة :attribute غير صالحة.',
    'alpha' => 'يجب أن يحتوي :attribute على أحرف.',
    'required_with' => 'قيمة :attribute غير صالحة.',
    'size' => ['string' => 'قيمة :attribute غير صالحة.'],
];
